import {
  common,
  steps,
  bed,
  effect,
  speech,
  music,
} from '../../../shared/audio/catalog-helpers';
import { farmDetailCatalog } from './detail-catalog';
const farm = [
  ...farmDetailCatalog,
  ...steps(['grass', 'hoof', 'wood']),
  bed(
    'site',
    'Pasture air',
    'Quiet late-morning meadow, distant scattered small birds and faint summer insects, open rural space. No cows close to microphone.',
    0.7,
  ),
  bed(
    'trees',
    'Meadow wind',
    'A mild country breeze passes through tall grass and a leafy hedgerow; subtle grass hiss under soft moving leaves. No microphone rumble.',
    0.65,
  ),
  bed(
    'fence',
    'Electric fence · powered',
    'Very quiet low-voltage fence energizer hum with soft regular subdued dry electrical ticks, contained source without arcing or threatening crackle.',
    0.55,
  ),
  bed(
    'panel',
    'Power switch · working',
    'Close small metal switch housing gently scraped and a stiff rotary mechanism being worked slowly by pressure, low-key metallic friction.',
    0.4,
  ),
  ...[1, 2, 3].map((v) =>
    effect(
      `animal.moo.${v}`,
      `Cow · call ${v}`,
      'Herd',
      [
        'One relaxed adult cow gives a low short chesty moo, gentle breathy ending, at a few metres distance.',
        'One adult cow gives a soft medium-length questioning moo, naturally rough chest resonance, quiet breath at the end.',
        'One adult cow gives a short nasal lowing sound with a small exhale, calm ordinary farm animal.',
      ][v - 1],
      2.5,
      0.55,
    ),
  ),
  ...[1, 2, 3].map((v) =>
    effect(
      `animal.graze.${v}`,
      `Grazing · bite ${v}`,
      'Herd',
      [
        'One cow tears a small mouthful of fresh grass; soft fibrous pluck and two quiet natural chews.',
        'One cow noses aside grass and bites; faint moist chewing and delicate grass friction.',
        'One cow slowly chews a mouthful of grass, soft jaw contact with a brief exhale and leaf movement.',
      ][v - 1],
      1.7,
      0.4,
    ),
  ),
  effect(
    'item.key.grab',
    'Pick up a key',
    'Keys',
    'One solid brass gate key lifted from grass, tiny grass brush and a short delicate metal jingle, no lock turning.',
    0.8,
    0.55,
  ),
  effect(
    'item.key.drop',
    'Drop a key',
    'Keys',
    'A single brass key falls a short distance into meadow grass; a tiny dull metal tap and soft grass contact.',
    0.8,
    0.5,
  ),
  effect(
    'item.key.unlock',
    'Unlock gate padlock',
    'Keys',
    'Brass key enters a sturdy steel padlock, turns with two precise metal clicks, then the shackle opens with a solid small clack.',
    1.6,
    0.65,
  ),
  effect(
    'item.ladder.grab',
    'Pick up ladder',
    'Ladder',
    'Lift an intact wooden farm ladder off turf; wood flex and paired rails lightly scraping grass, solid joints, no metallic rattle.',
    1.3,
    0.55,
  ),
  effect(
    'item.ladder.drop',
    'Drop ladder',
    'Ladder',
    'A wooden farm ladder settles onto grass; two spaced dull rail contacts and short rung vibration without damage.',
    1.3,
    0.6,
  ),
  effect(
    'item.ladder.place',
    'Lean ladder on fence',
    'Ladder',
    'Wooden ladder rails lean onto a sturdy timber fence, two hollow wood knocks and a brief loaded joint creak, feet settle in soil.',
    1.6,
  ),
  effect(
    'event.climb',
    'Climb out',
    'Escape',
    'Heavy cow weight climbs three wooden ladder rungs in slow sequence, low wood creaks and blunt hoof contacts. Ladder remains intact.',
    3,
    0.6,
  ),
  effect(
    'event.gate',
    'Pass through gate',
    'Escape',
    'A heavy timber farm gate opens on mildly dry iron hinges; low wood creak and hinge rub followed by a small latch rattle, no slam.',
    2,
  ),
  effect(
    'event.fence-shock',
    'Live fence shock',
    'Fence',
    'A sharp electric fence contact snap followed by a brief dry buzzing electrical discharge and a quick fading crackle. One short zap, no voice or music.',
    0.65,
    0.8,
  ),
  effect(
    'event.power-off',
    'Fence power off',
    'Fence',
    'A stiff outdoor electrical isolator clicks off; firm mechanical switch snap, brief relay clunk and a tiny hum tail winding down. No sparks.',
    1.1,
  ),
  effect(
    'event.inspect',
    'Farmer inspection',
    'Inspection',
    'Farmer takes one deliberate boot step and brushes a gloved hand against a cow’s short coat; quiet tactile fabric and hair contact.',
    1.2,
    0.5,
  ),
  effect(
    'event.capture',
    'Disguise discovered',
    'Inspection',
    'A loose fabric cow disguise rustles and bunches as its wearer is caught, soft padded movement and two surprised stopping footsteps. No violence or tearing.',
    1.5,
  ),
  speech(
    'start',
    'Round begins',
    'Keep it natural. The farmer is watching.',
    '[playfully]',
  ),
  speech(
    'inspect',
    'Farmer checks a cow',
    'Hold on. Let me have a look at you.',
    '[curious]',
  ),
  speech(
    'capture',
    'Farmer finds a friend',
    'I knew you were up to something.',
    '[playfully]',
  ),
  speech(
    'power-off',
    'Power is off',
    'The fence is quiet. That’s our chance.',
    '[whispering]',
  ),
  speech('escape', 'A cow escapes', 'One of them got out!', '[surprised]'),
  speech(
    'win',
    'Cows win',
    'Fresh grass on the other side. Nicely done.',
    '[pleased]',
  ),
  speech(
    'fail',
    'Farmer wins',
    'All accounted for. Better luck next time.',
    '[warmly]',
  ),
];
export const farmCatalog = [...common, ...farm, ...music('act-natural')];
