import { test } from 'node:test';
import assert from 'node:assert/strict';
import { act, createPlayer, freshWorld, movePlayer, placement, tick, waterAt } from './simulation';
import { dimensions, GOAL, type Piece } from './types';
const NOW=100000;
function setup(){const w=freshWorld(NOW);w.pieces=[];w.players=[createPlayer('a','Ada',0,0,NOW),createPlayer('b','Bo',1,1,NOW)];return w;}
const crate=(id:string,x=0,y=.13,z=0):Piece=>({id,kind:'crate',x,y,z,rotation:0,vy:0,tilt:0,unstable:0});
test('the initial salvage fits the yard without overlapping volumes',()=>{const w=freshWorld(NOW);assert.equal(w.pieces.length,28);for(const a of w.pieces){const da=dimensions(a);assert.ok(Math.abs(a.x)+da.w/2<10);assert.ok(Math.abs(a.z)+da.d/2<10);for(const b of w.pieces){if(a.id===b.id)continue;const db=dimensions(b);const collision=Math.abs(a.x-b.x)<(da.w+db.w)/2-.01&&Math.abs(a.z-b.z)<(da.d+db.d)/2-.01&&a.y<b.y+db.h-.01&&a.y+da.h>b.y+.01;assert.equal(collision,false,`${a.id} overlaps ${b.id}`);}}});
test('flood has a one minute grace period and follows elapsed wall time',()=>{const w=setup();w.phase='playing';w.started=NOW;assert.equal(waterAt(w,NOW+60000),-.4);assert.equal(waterAt(w,NOW+100000),.6);w.mode='practice';assert.equal(waterAt(w,NOW+1000000),-.4);});
test('unsupported tower falls after its bottom piece is removed',()=>{const w=setup();w.pieces=[crate('bottom'),crate('middle',0,1.43),crate('top',0,2.73)];tick(w,NOW+100);assert.ok(Math.abs(w.pieces[2].y-2.73)<.0001);w.pieces.shift();tick(w,NOW+1500);assert.ok(Math.abs(w.pieces[0].y-.13)<.01);assert.ok(Math.abs(w.pieces[1].y-1.43)<.01);});
test('centre-supported stack stays stable and overhangs eventually slide',()=>{const w=setup();w.pieces=[crate('bottom'),crate('top',1,1.43)];tick(w,NOW+1900);assert.ok(w.pieces[1].unstable>1);assert.ok(w.pieces[1].x>1);const stable=setup();stable.pieces=[crate('bottom'),crate('top',0,1.43)];tick(stable,NOW+1900);assert.equal(stable.pieces[1].unstable,0);assert.equal(stable.pieces[1].x,0);});
test('movement is normalized, bounded and collides with salvage',()=>{const w=setup(),p=w.players[0];p.x=0;p.z=0;for(let i=0;i<45;i++)movePlayer(w,p,1/45,{x:1,z:1,jump:false,seq:0});assert.ok(Math.hypot(p.x,p.z)<4.41);assert.ok(Math.hypot(p.x,p.z)>4.3);p.x=0;p.z=0;w.pieces=[crate('wall',2,.13,0)];for(let i=0;i<90;i++)movePlayer(w,p,1/45,{x:1,z:0,jump:false,seq:0});assert.ok(p.x<1);w.pieces=[];for(let i=0;i<200;i++)movePlayer(w,p,1/45,{x:-1,z:0,jump:false,seq:0});assert.ok(p.x>=-9.6);});
test('a jump lands on a crate and holding jump does not autojump',()=>{const w=setup(),p=w.players[0];p.x=0;p.z=0;w.pieces=[crate('step',2,.13,0)];let peak=0;for(let i=0;i<55;i++){movePlayer(w,p,1/60,{x:i<32?1:0,z:0,jump:true,seq:1});peak=Math.max(peak,p.y);}assert.ok(peak>1.75);assert.ok(Math.abs(p.y-1.43)<.0001);assert.equal(p.grounded,true);for(let i=0;i<30;i++)movePlayer(w,p,1/60,{x:0,z:0,jump:true,seq:1});assert.ok(Math.abs(p.y-1.43)<.0001);});
test('grab enforces reach and one holder, placement rejects player intersections',()=>{const w=setup(),p=w.players[0];p.x=0;p.z=0;w.pieces=[crate('near',2),crate('far',8)];assert.throws(()=>act(w,'a',{type:'grab',target:'far'},'a'),/out of reach/);act(w,'a',{type:'grab',target:'near'},'a');assert.equal(w.pieces[0].heldBy,'a');assert.throws(()=>act(w,'b',{type:'grab',target:'near'},'a'));assert.equal(placement(w,p,w.pieces[0],0,0).error,'Someone is standing there.');act(w,'a',{type:'place',x:2,z:2},'a');assert.equal(w.pieces[0].heldBy,undefined);assert.equal(w.pieces[0].y,.13);});
test('teammates can revive nearby players but cannot rescue at a distance',()=>{const w=setup(),[a,b]=w.players;a.x=0;a.z=0;b.x=2;b.z=0;b.down=true;b.breath=0;act(w,'a',{type:'rescue'},'a');assert.equal(b.down,false);assert.equal(b.breath,8);b.down=true;b.x=9;assert.throws(()=>act(w,'a',{type:'rescue'},'a'),/four metres/);});
test('drowning ends the round only when the whole crew is down',()=>{const w=setup();w.phase='playing';w.started=NOW-200000;w.clock=NOW;w.players[0].y=6;w.players[0].grounded=true;w.pieces=[crate('island',w.players[0].x,4.7,w.players[0].z)];w.players[1].breath=.05;tick(w,NOW+100);assert.equal(w.players[1].down,true);assert.equal(w.phase,'playing');w.players[0].down=true;tick(w,NOW+200);assert.equal(w.phase,'lost');});
test('one teammate reaching rescue saves the crew and restart clears the round',()=>{const w=setup();w.phase='playing';w.started=NOW;Object.assign(w.players[0],{x:0,y:GOAL,z:0});tick(w,NOW+30);assert.equal(w.phase,'won');assert.throws(()=>act(w,'b',{type:'restart'},'a'),/captain/);act(w,'a',{type:'restart'},'a');assert.equal(w.phase,'playing');assert.equal(w.players.length,2);assert.equal(w.players[0].y,.13);assert.equal(w.pieces.length,28);});
test('crane has one operator, bounded reach and returns cargo on release',()=>{const w=setup();w.pieces=[crate('load')];act(w,'a',{type:'crane',target:'load'},'a');assert.equal(w.pieces[0].heldBy,'crane');assert.throws(()=>act(w,'b',{type:'crane',target:'load'},'a'),/teammate/);for(let i=0;i<30;i++)act(w,'a',{type:'crane-move',x:100,z:-100,y:100},'a');assert.equal(w.crane.x,8);assert.equal(w.crane.z,-8);assert.ok(w.crane.y<=2.2);tick(w,NOW+20);act(w,'a',{type:'crane-drop'},'a');assert.equal(w.crane.owner,null);assert.equal(w.pieces[0].heldBy,undefined);});
test('rotated dimensions stay consistent with placement',()=>{assert.deepEqual(dimensions({...crate('a'),kind:'plank',rotation:1}),{w:1.2,h:.25,d:3.6});});

