export const ADVENTURE_COPY = {
  en: {
    tap: 'TAP A FRIEND FOR A TIP',
    crewLabels: {
      wave: 'Meet the game scout',
      point: 'Meet the explorer',
      cheer: 'Meet the stylist',
      mail: 'Meet the party host',
    },
    tips: {
      wave: 'Can’t decide? Let the surprise picker choose your next adventure!',
      point:
        'Visit a new game and collect its stamp in your passport. How many can you find?',
      cheer:
        'Your crew, your look! Open “Your look” to try on your first outfit.',
      mail: 'Friends coming over? Start party mode and share your room code. Let the chaos begin!',
    },
    desk: 'A little nudge into your next adventure.',
    pickLabel: 'THE CREW’S SURPRISE PICK',
    pickTitle: 'Where to next?',
    pickPersonal: 'Your next adventure',
    pickHint:
      'Give the crew a spin. We’ll pick somewhere you haven’t explored yet.',
    shuffle: 'Pick my next game',
    again: 'Pick another',
    shuffling: 'The crew is choosing…',
    revealed: 'Your next adventure is ready!',
    newPick: 'SOMEWHERE NEW',
    revisit: 'ANOTHER ROUND?',
    passport: 'Your adventure passport',
    passportLabel: 'JUMBLEYARD EXPLORER CLUB',
    saved: 'Saved in this browser. One stamp per game visited.',
    savedSignedIn:
      'You’re signed in. Stamps are saved on this device, one per game visited.',
    temporary: 'Storage is unavailable. Progress lasts for this visit only.',
    stamps: 'stamps collected',
    empty: 'Your first adventure goes here.',
    allStamps: 'Open the stamp collection',
    closeStamps: 'Close the stamp collection',
    collected: 'Visited',
    unvisited: 'Not visited yet',
    quests: 'Three little quests to get you going',
    style: 'Choose your look',
    styleHint: 'Wear something from your wardrobe.',
    first: 'Take the first leap',
    firstHint: 'Visit your first game.',
    three: 'Find your kind of chaos',
    threeHint: 'Explore three different games.',
    dress: 'Try an outfit',
    explore: 'Explore games',
    complete: 'Complete',
    questProgress: 'starter quests complete',
    welcome: 'Every adventure starts with a first step.',
    finished: 'The whole yard is yours!',
    celebration: 'Look at you go!',
    celebrationHint: 'Your passport has new progress. Keep exploring!',
    dismiss: 'Dismiss celebration',
  },
  de: {
    tap: 'TIPPE AUF EINEN FREUND FÜR EINEN TIPP',
    crewLabels: {
      wave: 'Triff den Spiele-Scout',
      point: 'Triff den Entdecker',
      cheer: 'Triff die Stylistin',
      mail: 'Triff den Party-Gastgeber',
    },
    tips: {
      wave: 'Du kannst dich nicht entscheiden? Lass uns dein nächstes Abenteuer auslosen!',
      point:
        'Besuche ein neues Spiel und sammle seinen Stempel in deinem Pass. Wie viele findest du?',
      cheer:
        'Deine Crew, dein Look! Öffne „Dein Look“ und probiere dein erstes Outfit an.',
      mail: 'Die Freunde kommen? Starte den Party-Modus und teile deinen Raumcode. Los geht’s!',
    },
    desk: 'Ein kleiner Schubs ins nächste Abenteuer.',
    pickLabel: 'DER ÜBERRASCHUNGSTIPP DER CREW',
    pickTitle: 'Wohin als Nächstes?',
    pickPersonal: 'Dein nächstes Abenteuer',
    pickHint:
      'Lass die Crew wählen. Wir suchen ein Spiel, das du noch nicht entdeckt hast.',
    shuffle: 'Wähle mein nächstes Spiel',
    again: 'Noch ein Vorschlag',
    shuffling: 'Die Crew überlegt…',
    revealed: 'Dein nächstes Abenteuer wartet!',
    newPick: 'ETWAS NEUES',
    revisit: 'NOCH EINE RUNDE?',
    passport: 'Dein Abenteuerpass',
    passportLabel: 'JUMBLEYARD ENTDECKERCLUB',
    saved: 'In diesem Browser gespeichert. Ein Stempel pro besuchtem Spiel.',
    savedSignedIn:
      'Du bist angemeldet. Stempel werden auf diesem Gerät gespeichert, einer pro besuchtem Spiel.',
    temporary:
      'Speichern ist nicht möglich. Dein Fortschritt gilt nur für diesen Besuch.',
    stamps: 'Stempel gesammelt',
    empty: 'Hier beginnt dein erstes Abenteuer.',
    allStamps: 'Stempelsammlung öffnen',
    closeStamps: 'Stempelsammlung schließen',
    collected: 'Besucht',
    unvisited: 'Noch nicht besucht',
    quests: 'Drei kleine Aufgaben zum Loslegen',
    style: 'Finde deinen Look',
    styleHint: 'Trage etwas aus deinem Kleiderschrank.',
    first: 'Wage den ersten Sprung',
    firstHint: 'Besuche dein erstes Spiel.',
    three: 'Finde dein Lieblingschaos',
    threeHint: 'Entdecke drei verschiedene Spiele.',
    dress: 'Outfit anprobieren',
    explore: 'Spiele entdecken',
    complete: 'Geschafft',
    questProgress: 'Startaufgaben geschafft',
    welcome: 'Jedes Abenteuer beginnt mit einem ersten Schritt.',
    finished: 'Die ganze Spielwiese gehört dir!',
    celebration: 'Das läuft bei dir!',
    celebrationHint: 'Dein Pass hat neue Fortschritte. Entdecke noch mehr!',
    dismiss: 'Glückwunsch schließen',
  },
};
