import { cue } from '../../../shared/audio/catalog-helpers';

export const expansion = [
  cue(
    'event.ui',
    'Rink control',
    'Immersive details',
    'Small wooden toggle click. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.3,
  ),
  cue(
    'curling.launch',
    'Stone release',
    'Immersive details',
    'Leather glove releases granite with a short ice swish. Original playful Foley, no speech. ',
    'event',
    0.7,
    false,
    0.6,
  ),
  cue(
    'curling.hairdryer',
    'Hairdryer sweep',
    'Immersive details',
    'Compact electric fan whir with warm airflow. Original playful Foley, no speech. ',
    'event',
    0.7,
    false,
    0.5,
  ),
  cue(
    'curling.blowtorch',
    'Torch sweep',
    'Immersive details',
    'Short gas ignition puff and flame hiss. Original playful Foley, no speech. ',
    'event',
    0.7,
    false,
    0.5,
  ),
  cue(
    'curling.banana_toss',
    'Banana toss',
    'Immersive details',
    'Quick soft throw swish and peel slap. Original playful Foley, no speech. ',
    'event',
    0.6,
    false,
    0.5,
  ),
  cue(
    'curling.out',
    'Stone out',
    'Immersive details',
    'Granite scraping to a stop with a dull end-stop thump. Original playful Foley, no speech. ',
    'event',
    0.8,
    false,
    0.6,
  ),
  cue(
    'curling.turn',
    'Your next throw',
    'Immersive details',
    'Two bright rink bell notes. Original playful Foley, no speech. ',
    'event',
    0.8,
    false,
    0.5,
  ),
  cue(
    'curling.match',
    'Match complete',
    'Immersive details',
    'Warm bright bell flourish and brushed cymbal. Original playful Foley, no speech. ',
    'event',
    2,
    false,
    0.65,
  ),
  cue(
    'event.jump',
    'Ice hop',
    'Immersive details',
    'Boot lifts off crisp snow. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.3,
  ),
  cue(
    'event.land',
    'Ice landing',
    'Immersive details',
    'Boots land with gritty ice crunch. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.4,
  ),
  cue(
    'ambience.rink',
    'Rink air',
    'Immersive details',
    'Soft winter air with distant enclosed rink ventilation. Original playful Foley, no speech. Seamless loop with no fade.',
    'ambience',
    4,
    true,
    0.4,
  ),
  cue(
    'music.play',
    'Curling groove',
    'Immersive details',
    'Sparse glockenspiel and brushed hand percussion. Original playful Foley, no speech. Seamless loop with no fade.',
    'music',
    8,
    true,
    0.35,
  ),
  cue(
    'event.step.1',
    'Footstep 1',
    'Immersive details',
    'Single boot crunch on gritty ice. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.32,
  ),
  cue(
    'event.step.2',
    'Footstep 2',
    'Immersive details',
    'Single boot crunch on gritty ice. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.32,
  ),
  cue(
    'event.step.3',
    'Footstep 3',
    'Immersive details',
    'Single boot crunch on gritty ice. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.32,
  ),
];
