import type { Localized } from '../../shared/language/types';

const en = {
  brief: 'Keep it level. Leave it spotless.',
  intro:
    'Clean 30 windows before the helicopter arrives. Your bot crew handles the other jobs.',
  crew: 'Your crew assignment',
  left: 'Raise or lower the left side. Match your partner to keep the deck level.',
  right:
    'Raise or lower the right side. Match your partner to keep the deck level.',
  cleaner: 'Soap dirty glass, then switch to the squeegee. A good first shift.',
  all: 'Move, clean, and operate either winch. Your bot crew still helps.',
  start: 'Start shift',
  steps: ['Soap', 'Switch tool', 'Squeegee'],
  goal: 'windows',
  duration: 'per shift',
  bots: 'bot crewmates',
  move: 'Move along the deck to reach a dirty window.',
  soap: 'Dirty glass in reach. Use the sponge to add soap.',
  wipe: 'Foamed glass in reach. Use the squeegee to finish.',
  switchSoap: 'Switch to the sponge first, then soap the glass.',
  switchWipe: 'Soap is on! Switch to the squeegee to finish.',
  done: 'This window is spotless. Move to the next one.',
  climb: 'Hold the action button or Space to climb back up.',
  balance: 'Deck tilting! Raise the low side or lower the high side.',
  shoo: 'A pigeon is in reach. Use the action button to shoo it.',
  winch:
    'Hold your winch controls to reach the next row. Keep both sides level.',
  action: 'Use tool',
  climbAction: 'Climb up',
  swap: 'Switch tool',
  leftUp: 'Raise left winch',
  leftDown: 'Lower left winch',
  rightUp: 'Raise right winch',
  rightDown: 'Lower right winch',
  moveLeft: 'Move left',
  moveRight: 'Move right',
  cleaned: 'Window spotless!',
  personal: 'You cleaned',
  slips: 'Your slips',
  crewTotal: 'Crew total',
  retryTip: 'Next shift: soap first, squeegee second. Keep the cradle level.',
  timeRemaining: 'Time remaining',
};
export const SCAFFOLD_UI: Localized<typeof en> = {
  en,
  de: {
    brief: 'Gerade halten. Sauber abziehen.',
    intro:
      'Putzt 30 Fenster, bevor der Hubschrauber landet. Eure Bot-Crew übernimmt die anderen Aufgaben.',
    crew: 'Deine Aufgabe im Team',
    left: 'Hebe oder senke die linke Seite. Halte mit deinem Partner die Gondel gerade.',
    right:
      'Hebe oder senke die rechte Seite. Halte mit deinem Partner die Gondel gerade.',
    cleaner:
      'Glas einseifen, dann zum Abzieher wechseln. Ideal für die erste Schicht.',
    all: 'Laufen, putzen und beide Winden bedienen. Die Bot-Crew hilft weiterhin.',
    start: 'Schicht starten',
    steps: ['Einseifen', 'Wechseln', 'Abziehen'],
    goal: 'Fenster',
    duration: 'pro Schicht',
    bots: 'Bot-Kollegen',
    move: 'Gehe auf der Gondel zu einem schmutzigen Fenster.',
    soap: 'Schmutziges Glas in Reichweite. Mit dem Schwamm einseifen.',
    wipe: 'Eingeseiftes Glas in Reichweite. Mit dem Abzieher fertig putzen.',
    switchSoap: 'Wechsle zuerst zum Schwamm und seife das Glas ein.',
    switchWipe: 'Eingeseift! Wechsle zum Abzieher, um fertig zu putzen.',
    done: 'Dieses Fenster ist sauber. Weiter zum nächsten.',
    climb: 'Halte die Aktionstaste oder Leertaste, um hochzuklettern.',
    balance: 'Die Gondel kippt! Hebe die tiefe oder senke die hohe Seite.',
    shoo: 'Eine Taube ist in Reichweite. Verscheuche sie mit der Aktionstaste.',
    winch:
      'Halte die Windensteuerung für die nächste Reihe. Halte beide Seiten gerade.',
    action: 'Benutzen',
    climbAction: 'Hochklettern',
    swap: 'Werkzeug wechseln',
    leftUp: 'Linke Winde heben',
    leftDown: 'Linke Winde senken',
    rightUp: 'Rechte Winde heben',
    rightDown: 'Rechte Winde senken',
    moveLeft: 'Nach links',
    moveRight: 'Nach rechts',
    cleaned: 'Fenster blitzblank!',
    personal: 'Von dir geputzt',
    slips: 'Ausgerutscht',
    crewTotal: 'Team-Ergebnis',
    retryTip:
      'Nächste Schicht: erst einseifen, dann abziehen. Haltet die Gondel gerade.',
    timeRemaining: 'Verbleibende Zeit',
  },
};
