import { cue } from '../../../shared/audio/catalog-helpers';

export const expansion = [
  cue(
    'event.ui',
    'Arena control',
    'Immersive details',
    'Small rubber switch pop. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.3,
  ),
  cue(
    'event.recover',
    'Back on your feet',
    'Immersive details',
    'Inflatable rubber pop and upward elastic twang. Original playful Foley, no speech. ',
    'event',
    0.7,
    false,
    0.6,
  ),
  cue(
    'event.land',
    'Bubble landing',
    'Immersive details',
    'Soft hollow inflatable ball landing. Original playful Foley, no speech. ',
    'event',
    0.6,
    false,
    0.55,
  ),
  cue(
    'event.jump',
    'Bubble lift',
    'Immersive details',
    'Soft rubber stretch. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.3,
  ),
  cue(
    'event.countdown',
    'Kickoff tick',
    'Immersive details',
    'Short sports clock woodblock. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.5,
  ),
  cue(
    'event.win',
    'Final whistle flourish',
    'Immersive details',
    'Bright rising brass and percussion finish. Original playful Foley, no speech. ',
    'event',
    2,
    false,
    0.7,
  ),
  cue(
    'event.warning',
    'Final ten seconds',
    'Immersive details',
    'Short clock bell. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.5,
  ),
  cue(
    'ambience.crowd',
    'Stadium atmosphere',
    'Immersive details',
    'Soft diffuse crowd movement and distant claps without words. Original playful Foley, no speech. Seamless loop with no fade.',
    'ambience',
    4,
    true,
    0.4,
  ),
  cue(
    'ambience.roll',
    'Bubble rolling',
    'Immersive details',
    'Soft textured rubber rubbing across turf. Original playful Foley, no speech. Seamless loop with no fade.',
    'ambience',
    4,
    true,
    0.4,
  ),
  cue(
    'ambience.charge',
    'Dash charging',
    'Immersive details',
    'Rising elastic tension with gentle humming air. Original playful Foley, no speech. Seamless loop with no fade.',
    'ambience',
    4,
    true,
    0.45,
  ),
  cue(
    'music.play',
    'Bumper groove',
    'Immersive details',
    'Bouncy marimba and rubbery plucked bass rhythm. Original playful Foley, no speech. Seamless loop with no fade.',
    'music',
    8,
    true,
    0.4,
  ),
  cue(
    'event.step.1',
    'Footstep 1',
    'Immersive details',
    'Single soft rubbery footstep on grass. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.32,
  ),
  cue(
    'event.step.2',
    'Footstep 2',
    'Immersive details',
    'Single soft rubbery footstep on grass. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.32,
  ),
  cue(
    'event.step.3',
    'Footstep 3',
    'Immersive details',
    'Single soft rubbery footstep on grass. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.32,
  ),
];
