import { cue } from '../../../shared/audio/catalog-helpers';

export const expansion = [
  cue(
    'event.ui',
    'Control click',
    'Immersive details',
    'Small metal switch click. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.3,
  ),
  cue(
    'event.cable',
    'Cable takes the load',
    'Immersive details',
    'Steel cable tightens with a creak and pulley rattle. Original playful Foley, no speech. ',
    'event',
    0.9,
    false,
    0.6,
  ),
  cue(
    'event.impact-stone',
    'Concrete landing',
    'Immersive details',
    'Concrete block drops with a dusty low stone crack. Original playful Foley, no speech. ',
    'event',
    1,
    false,
    0.75,
  ),
  cue(
    'event.impact-metal',
    'Steel landing',
    'Immersive details',
    'Hollow steel beam impact with metallic resonances. Original playful Foley, no speech. ',
    'event',
    1,
    false,
    0.65,
  ),
  cue(
    'event.warning',
    'Last ten seconds',
    'Immersive details',
    'Short industrial clock bell. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.55,
  ),
  cue(
    'event.draw',
    'Draw result',
    'Immersive details',
    'Two warm descending bell notes. Original playful Foley, no speech. ',
    'event',
    1.4,
    false,
    0.6,
  ),
  cue(
    'ambience.swing',
    'Swinging cable air',
    'Immersive details',
    'Soft airy cable movement and rope friction. Original playful Foley, no speech. Seamless loop with no fade.',
    'ambience',
    4,
    true,
    0.4,
  ),
  cue(
    'music.play',
    'Crane yard groove',
    'Immersive details',
    'Light syncopated plucked bass, wooden percussion and mallets. Original playful Foley, no speech. Seamless loop with no fade.',
    'music',
    8,
    true,
    0.4,
  ),
];
