import { cue } from '../../../shared/audio/catalog-helpers';

export const expansion = [
  cue(
    'event.ui',
    'Siege control',
    'Immersive details',
    'Wooden lever click. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.3,
  ),
  cue(
    'event.jump',
    'Crew jump',
    'Immersive details',
    'Leather boots push off dry earth. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.4,
  ),
  cue(
    'event.land',
    'Crew landing',
    'Immersive details',
    'Heavy boots land in dirt. Original playful Foley, no speech. ',
    'event',
    0.6,
    false,
    0.5,
  ),
  cue(
    'event.ready',
    'Winch fully wound',
    'Immersive details',
    'Ratchet stop and taut rope twang. Original playful Foley, no speech. ',
    'event',
    0.9,
    false,
    0.6,
  ),
  cue(
    'event.turn',
    'Engine turns',
    'Immersive details',
    'Wooden wheel creaks across dry earth. Original playful Foley, no speech. ',
    'event',
    0.8,
    false,
    0.5,
  ),
  cue(
    'event.flyby',
    'Payload flight',
    'Immersive details',
    'Heavy projectile rushes through air. Original playful Foley, no speech. ',
    'event',
    1.2,
    false,
    0.6,
  ),
  cue(
    'event.relief',
    'Relief arrives',
    'Immersive details',
    'Two distant warm horn calls. Original playful Foley, no speech. ',
    'event',
    2,
    false,
    0.7,
  ),
  cue(
    'event.lose',
    'Assault ends',
    'Immersive details',
    'Low descending plucked string and drum cadence. Original playful Foley, no speech. ',
    'event',
    2,
    false,
    0.6,
  ),
  cue(
    'ambience.winch',
    'Winch under load',
    'Immersive details',
    'Steady wooden ratchet clicking with low rope groans. Original playful Foley, no speech. Seamless loop with no fade.',
    'ambience',
    4,
    true,
    0.55,
  ),
  cue(
    'ambience.bees',
    'Swarm nearby',
    'Immersive details',
    'Soft layered buzzing wings. Original playful Foley, no speech. Seamless loop with no fade.',
    'ambience',
    4,
    true,
    0.4,
  ),
  cue(
    'ambience.flight',
    'Incoming air',
    'Immersive details',
    'Low airy projectile wind rush. Original playful Foley, no speech. Seamless loop with no fade.',
    'ambience',
    4,
    true,
    0.3,
  ),
  cue(
    'event.step.1',
    'Footstep 1',
    'Immersive details',
    'Single leather boot on dry gravel. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.32,
  ),
  cue(
    'event.step.2',
    'Footstep 2',
    'Immersive details',
    'Single leather boot on dry gravel. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.32,
  ),
  cue(
    'event.step.3',
    'Footstep 3',
    'Immersive details',
    'Single leather boot on dry gravel. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.32,
  ),
];
