import { cue } from '../../../shared/audio/catalog-helpers';

export const expansion = [
  cue(
    'event.ui',
    'Control click',
    'Immersive details',
    'Dry switch click. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.3,
  ),
  cue(
    'event.crane',
    'Crane controls',
    'Immersive details',
    'Lever clunk and relay click. Original playful Foley, no speech. ',
    'event',
    0.65,
    false,
    0.6,
  ),
  cue(
    'event.swing',
    'Hammer swing',
    'Immersive details',
    'Short weighty air swish. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.45,
  ),
  cue(
    'event.strain',
    'Support strain',
    'Immersive details',
    'Loaded timber creaks and masonry grit falls. Original playful Foley, no speech. ',
    'event',
    1.3,
    false,
    0.6,
  ),
  cue(
    'event.piano-danger',
    'Piano danger',
    'Immersive details',
    'Uneasy piano string rattle and two low notes. Original playful Foley, no speech. ',
    'event',
    1.3,
    false,
    0.6,
  ),
  cue(
    'event.jump',
    'Work boot jump',
    'Immersive details',
    'Boot pushes off dusty ground. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.4,
  ),
  cue(
    'event.land',
    'Boot landing',
    'Immersive details',
    'Two work boots thud into gravel. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.5,
  ),
  cue(
    'event.warning',
    'Last ten seconds',
    'Immersive details',
    'Brief construction clock bell. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.5,
  ),
  cue(
    'ambience.debris',
    'Falling debris',
    'Immersive details',
    'Soft falling grit and intermittent pebble rattle. Original playful Foley, no speech. Seamless loop with no fade.',
    'ambience',
    4,
    true,
    0.45,
  ),
  cue(
    'music.play',
    'Demolition groove',
    'Immersive details',
    'Low pizzicato bass and sparse woodblock pulse. Original playful Foley, no speech. Seamless loop with no fade.',
    'music',
    8,
    true,
    0.4,
  ),
  cue(
    'event.step.1',
    'Footstep 1',
    'Immersive details',
    'Single leather boot on dry gravel. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.32,
  ),
  cue(
    'event.step.2',
    'Footstep 2',
    'Immersive details',
    'Single leather boot on dry gravel. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.32,
  ),
  cue(
    'event.step.3',
    'Footstep 3',
    'Immersive details',
    'Single leather boot on dry gravel. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.32,
  ),
];
