import { cue } from '../../../shared/audio/catalog-helpers';

const effects: [string, string, string, number, number][] = [
  [
    'punch',
    'Glove swing',
    'Short leather glove swish through air.',
    0.28,
    0.45,
  ],
  [
    'hit',
    'Jab impact',
    'Close padded glove slap with a soft body thump.',
    0.32,
    0.85,
  ],
  ['hit.1', 'Jab variation', 'Alternate dry padded glove impact.', 0.32, 0.85],
  [
    'hit.2',
    'Jab variation II',
    'Alternate rounded leather glove slap.',
    0.32,
    0.85,
  ],
  [
    'heavy',
    'Heavy punch',
    'Weighty padded cross or hook with a short room tail.',
    0.45,
    0.9,
  ],
  [
    'kick-hit',
    'Kick impact',
    'Deep padded shin impact with a broad cloth slap.',
    0.48,
    0.9,
  ],
  [
    'block',
    'Guard contact',
    'Muted double glove clap against a raised guard.',
    0.3,
    0.65,
  ],
  [
    'parry',
    'Timed parry',
    'Sharp glancing leather tap and short swish.',
    0.28,
    0.7,
  ],
  [
    'counter',
    'Counter punch',
    'Strong padded impact with a deep punchy accent.',
    0.5,
    0.95,
  ],
  [
    'guard-break',
    'Guard break',
    'Two gloves knocked apart with a double thump.',
    0.5,
    0.8,
  ],
  ['miss', 'Missed swing', 'Airy wide glove swing.', 0.4, 0.4],
  ['kick', 'Kick swing', 'Broad fast martial arts kick whoosh.', 0.4, 0.55],
  [
    'down',
    'Knockdown',
    'Body landing on sprung canvas with a low mat boom.',
    0.95,
    0.95,
  ],
  [
    'clinch',
    'Clinch contact',
    'Close cloth scuffle and feet scraping canvas.',
    0.5,
    0.65,
  ],
  [
    'takedown',
    'Takedown impact',
    'Weighty padded mat landing with canvas slap and resonance.',
    0.9,
    1,
  ],
  [
    'escape',
    'Grappling escape',
    'Quick cloth slide and palm push across canvas.',
    0.5,
    0.6,
  ],
  [
    'advance',
    'Ground position',
    'Two short cloth scuffs on a padded mat.',
    0.5,
    0.55,
  ],
  [
    'submission',
    'Submission attempt',
    'Taut cloth creak and a low tension accent.',
    0.65,
    0.5,
  ],
  [
    'bell',
    'Round starts',
    'Bright metal fight bell with a warm ringing decay.',
    1.8,
    0.8,
  ],
  [
    'round-end',
    'Round ends',
    'Three quick metal fight bell strikes.',
    2.2,
    0.8,
  ],
  ['countdown', 'Countdown', 'Dry wooden countdown knock.', 0.22, 0.55],
  [
    'warning',
    'Ten seconds left',
    'Three sharp wooden clacks for the last ten seconds.',
    0.65,
    0.7,
  ],
  [
    'step.1',
    'Canvas step',
    'Soft bare foot plant and canvas scuff.',
    0.24,
    0.42,
  ],
  [
    'step.2',
    'Canvas step II',
    'Alternate bare foot shuffle on canvas.',
    0.24,
    0.42,
  ],
  [
    'step.3',
    'Canvas step III',
    'Light foot pivot on a padded canvas mat.',
    0.24,
    0.42,
  ],
  ['dodge', 'Dodge', 'Fast clothes swish and foot slide.', 0.3, 0.45],
  [
    'fence',
    'Cage contact',
    'Brief chain link fence rattle with a low frame resonance.',
    0.7,
    0.55,
  ],
  [
    'breath',
    'Low stamina',
    'Short exertion breath, unvoiced airy exhale.',
    0.8,
    0.35,
  ],
  [
    'cheer',
    'Crowd cheer',
    'Small arena audience rising in a wordless cheer and applause.',
    2.8,
    0.48,
  ],
  [
    'gasp',
    'Crowd gasp',
    'Short collective wordless audience reaction.',
    1.5,
    0.4,
  ],
  [
    'win',
    'Victory',
    'Warm uplifting brass-like three note victory flourish.',
    2.5,
    0.65,
  ],
  [
    'loss',
    'Defeat',
    'Soft descending low three note match ending flourish.',
    2.2,
    0.5,
  ],
  ['draw', 'Draw', 'Two warm suspended notes resolving neutrally.', 2.2, 0.5],
];

export const cageCatalog = [
  ...effects.map(([id, name, prompt, duration, volume]) =>
    cue(
      `cage.${id}`,
      name,
      'Fight sounds',
      prompt,
      'event',
      Math.max(0.5, duration),
      false,
      volume,
    ),
  ),
  cue(
    'event.ui',
    'Selection click',
    'Interface',
    'Small warm wooden click.',
    'event',
    0.5,
    false,
    0.4,
  ),
  cue(
    'ambience.crowd',
    'Arena crowd',
    'Arena',
    'Wide quiet indoor audience murmur with distant applause, no intelligible words.',
    'ambience',
    12,
    true,
    0.7,
  ),
  cue(
    'ambience.grapple',
    'Ground scuffle',
    'Arena',
    'Gentle intermittent cloth and canvas friction.',
    'ambience',
    4,
    true,
    0.35,
  ),
  cue(
    'ambience.tension',
    'Submission tension',
    'Arena',
    'Soft rhythmic low pulse under a submission attempt.',
    'ambience',
    4,
    true,
    0.4,
  ),
  cue(
    'music.arena',
    'Fight night',
    'Music',
    'Restrained energetic percussion and low bass ostinato, no vocals.',
    'music',
    8,
    true,
    0.6,
  ),
];
