import { cue } from '../../../shared/audio/catalog-helpers';
import type { Cue } from '../../../shared/audio/types';
const show =
  'Original playful toy game-show sound. Bright, tactile, exaggerated comic timing, clean mix, no speech.';
const fx = (
  id: string,
  name: string,
  prompt: string,
  duration: number,
  volume = 0.75,
) =>
  cue(
    id,
    name,
    'Game-show chaos',
    `${prompt} ${show}`,
    'event',
    Math.max(0.5, duration),
    false,
    volume,
  );
export const buttonCatalog: Cue[] = [
  fx(
    'event.start',
    'Here comes trouble',
    'A bright brass and marimba welcome sting with snare flourish.',
    2.1,
  ),
  fx(
    'event.press',
    'The expensive button',
    'Heavy plastic button clunk, chunky spring release, a cash-register ding and tumbling coins.',
    1.35,
    0.9,
  ),
  fx(
    'event.warning',
    'Bad idea alarm',
    'Three short ascending cartoon warning buzzers.',
    1.1,
  ),
  fx(
    'event.punch',
    'Absolutely launched',
    'A huge padded boxing glove thwack with elastic boing and rattling percussion.',
    1.1,
    0.9,
  ),
  fx(
    'event.hit',
    'Sofa to the face',
    'A heavy upholstered thud, creaking springs and a comic wood clatter.',
    0.8,
  ),
  fx(
    'event.fall',
    'Off the stage',
    'A falling slide whistle followed by a soft crash and little bouncing objects.',
    1.4,
  ),
  fx(
    'event.escape',
    'Money in the bank',
    'A triumphant register bell arpeggio, fluttering coins and a tiny success fanfare.',
    1.8,
  ),
  fx(
    'event.stop',
    'STOP means STOP',
    'A panicked double clown horn, with a rubber squeak at the end.',
    0.75,
  ),
  fx(
    'event.finish',
    'We kept the money',
    'Short upbeat brass victory sting, drum fill and cheerful cymbal.',
    2.8,
  ),
  fx(
    'event.bust',
    'We were rich',
    'A descending comic wah-wah trombone with a final tiny sad bell.',
    2.4,
  ),
  fx(
    'event.glove-windup',
    'Glove charging',
    'A pneumatic pressure build and a rising ratchet ending before impact.',
    1.1,
    0.72,
  ),
  fx(
    'event.glove-fire',
    'Glove fires',
    'A spring slams forward, compressed-air whoosh and giant elastic twang.',
    0.7,
    0.85,
  ),
  fx(
    'event.hazard',
    'New terrible idea',
    'Mechanical shutters open, gears chatter and a cheerful terrible-idea ding.',
    1.25,
  ),
  fx(
    'event.slip',
    'No grip',
    'A wet soap squeak and a slippery upward then downward whistle.',
    0.65,
    0.6,
  ),
  fx(
    'event.jump',
    'Hop to it',
    'A short springy rubber-shoe jump swish.',
    0.25,
    0.45,
  ),
  fx(
    'event.land',
    'Feet first',
    'Two soft sneaker thumps on a hollow game-show stage.',
    0.23,
    0.45,
  ),
  fx(
    'event.step',
    'Stage footsteps',
    'A single light squeaky sneaker contact on a wooden stage.',
    0.15,
    0.32,
  ),
  fx(
    'event.door-open',
    'Escape is open',
    'A happy two-tone door chime and quick mechanical latch.',
    0.7,
    0.72,
  ),
  fx(
    'event.tick',
    'Last ten seconds',
    'A very short bright woodblock countdown tick.',
    0.14,
    0.65,
  ),
  fx(
    'event.crowd-cheer',
    'The audience loves this',
    'Small studio audience applause, playful whistles and excited rustling, no intelligible words.',
    2.5,
    0.55,
  ),
  fx(
    'event.crowd-gasp',
    'The audience saw that',
    'A quick startled studio-audience inhalation, squeaks and nervous movement, no words.',
    1.2,
    0.5,
  ),
  fx('event.ui', 'Show control', 'A tiny tactile toy-switch click.', 0.12, 0.3),
  cue(
    'ambience.conveyor',
    'Conveyor motors',
    'Room machinery',
    'Rhythmic low motor rattle and clacking rollers. Seamless mechanical loop, no music.',
    'ambience',
    4,
    true,
    0.5,
  ),
  cue(
    'ambience.spinner',
    'Furniture carousel',
    'Room machinery',
    'Comically squeaking springs and wooden bearings rotating steadily. Seamless mechanical loop, no music.',
    'ambience',
    4,
    true,
    0.55,
  ),
  cue(
    'ambience.soap',
    'Bubble trouble',
    'Room machinery',
    'Soft fizzy soap bubbles and tiny wet pops. Seamless loop, no music.',
    'ambience',
    4,
    true,
    0.42,
  ),
  ...(
    [
      [
        'show',
        'Questionable decisions',
        120,
        16,
        'Bouncy marimba melody, plucked bass, cheeky brass stabs, handclaps, swinging drums.',
      ],
      [
        'chaos',
        'Someone pressed again',
        144,
        40 / 3,
        'The same game-show melody with faster bass, busy percussion and more urgent brass.',
      ],
      [
        'escape',
        'Take the money and RUN',
        168,
        80 / 7,
        'Frantic chase variation with fast marimba, urgent bass, snare rolls and comic brass.',
      ],
    ] as const
  ).map(([id, name, bpm, duration, description]) =>
    cue(
      `music.${id}`,
      name,
      'Original game-show soundtrack',
      `Original instrumental cartoon game-show score, ${bpm} BPM. ${description} Seamless eight-bar loop; no vocals, no fade-out, leave room for game effects and voice chat.`,
      'music',
      duration,
      true,
      0.85,
    ),
  ),
];
