import { cue } from '../../../shared/audio/catalog-helpers';

export const expansion = [
  cue(
    'event.door-close',
    'Exit locks',
    'Immersive details',
    'Metal latch shuts with a low two-note clunk. Original playful Foley, no speech. ',
    'event',
    0.6,
    false,
    0.6,
  ),
  cue(
    'event.low-heart',
    'Last heart',
    'Immersive details',
    'Soft double heartbeat warning. Original playful Foley, no speech. ',
    'event',
    0.65,
    false,
    0.55,
  ),
  cue(
    'event.reward',
    'Prize grows',
    'Immersive details',
    'Coins bouncing with bright ascending metallic pings. Original playful Foley, no speech. ',
    'event',
    1,
    false,
    0.55,
  ),
  cue(
    'event.conveyor-start',
    'Conveyor starts',
    'Immersive details',
    'Motor relay clicks then belt catches. Original playful Foley, no speech. ',
    'event',
    0.8,
    false,
    0.6,
  ),
  cue(
    'event.spinner-start',
    'Carousel starts',
    'Immersive details',
    'Spring ratchets and squeaky bearing spins up. Original playful Foley, no speech. ',
    'event',
    0.8,
    false,
    0.6,
  ),
  cue(
    'event.soap-start',
    'Soap release',
    'Immersive details',
    'Pump splutters and bubbly spray spills out. Original playful Foley, no speech. ',
    'event',
    1,
    false,
    0.6,
  ),
  cue(
    'ambience.studio',
    'Studio room tone',
    'Immersive details',
    'Quiet ventilator and gentle diffuse room air. Original playful Foley, no speech. Seamless loop with no fade.',
    'ambience',
    4,
    true,
    0.28,
  ),
  cue(
    'event.step.1',
    'Footstep 1',
    'Immersive details',
    'Single sneaker tap on hollow wooden stage. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.32,
  ),
  cue(
    'event.step.2',
    'Footstep 2',
    'Immersive details',
    'Single sneaker tap on hollow wooden stage. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.32,
  ),
  cue(
    'event.step.3',
    'Footstep 3',
    'Immersive details',
    'Single sneaker tap on hollow wooden stage. Original playful Foley, no speech. ',
    'event',
    0.5,
    false,
    0.32,
  ),
];
