export const SAYINGS = [
  'It was like that when I got here!',
  'Fits. Wobbles. Plenty of ventilation.',
  'That is load-bearing decor.',
  'One more turn and it snaps.',
  'I saw this on the internet.',
  'That angle is artistic license.',
  'Measure twice. Get it wrong anyway.',
  'It is still drying.',
  'That screw was a spare.',
  'The boss wanted it that way.',
  'Just five more minutes!',
  'It will hold until the inspection.',
];
export const CATALOG = [
  {
    id: 'bookshelf',
    name: 'Bookcase',
    category: 'Furniture',
    color: '#bf956d',
    description: 'A whole shelf of instructions nobody read.',
  },
  {
    id: 'wardrobe',
    name: 'Wardrobe',
    category: 'Furniture',
    color: '#79b8a5',
    description: 'Room for every questionable outfit.',
  },
  {
    id: 'counter',
    name: 'Kitchen counter',
    category: 'Furniture',
    color: '#7bc9b0',
    description: 'A proper kitchen starts with somewhere to make a mess.',
  },
  {
    id: 'sink',
    name: 'Kitchen sink',
    category: 'Furniture',
    color: '#8ec8bb',
    description: 'Clean hands, clean conscience. X to turn on the tap.',
  },
  {
    id: 'stove',
    name: 'Cooker',
    category: 'Furniture',
    color: '#f3f2df',
    description: 'Dinner is a team effort. X to cook something.',
  },
  {
    id: 'bathtub',
    name: 'Bathtub',
    category: 'Furniture',
    color: '#95d2d7',
    description: 'A bath big enough for your building regrets. X for bubbles.',
  },
  {
    id: 'tv',
    name: 'Television',
    category: 'Furniture',
    color: '#548dc5',
    description: 'The renovation channel is taking notes. X to switch it on.',
  },
  {
    id: 'piano',
    name: 'Piano',
    category: 'Furniture',
    color: '#805d45',
    description: 'Heavy lifting, light entertainment. X to play.',
  },
  {
    id: 'bench',
    name: 'Garden bench',
    category: 'Furniture',
    color: '#7bc9b0',
    description: 'The patio deserves a proper tea break.',
  },
  {
    id: 'aquarium',
    name: 'Aquarium',
    category: 'Decor',
    color: '#548dc5',
    description: 'The quietest members of the crew. X to feed the fish.',
  },
  {
    id: 'easel',
    name: 'Painting easel',
    category: 'Decor',
    color: '#e7a4bd',
    description: 'Turn the building site into a studio. X to paint a picture.',
  },
  {
    id: 'doghouse',
    name: 'Dog house',
    category: 'Decor',
    color: '#e78268',
    description: 'A little house beside your bigger house.',
  },
  {
    id: 'stairs',
    name: 'Stairs',
    category: 'House',
    color: '#c1976b',
    description:
      'Walk between floors. The arrow points upstairs; leave the stairwell open.',
  },
  {
    id: 'fridge',
    name: 'Fridge',
    category: 'Furniture',
    color: '#8ec8bb',
    description: 'Cold drinks. Warm excuses. X to check inside.',
  },
  {
    id: 'washer',
    name: 'Washing machine',
    category: 'Furniture',
    color: '#dce8e4',
    description: 'The spin cycle has ambitions. X to test it.',
  },
  {
    id: 'clock',
    name: 'Grandfather clock',
    category: 'Decor',
    color: '#b88452',
    description: 'Even the furniture wants to clock off. X to wind it.',
  },
  {
    id: 'duck',
    name: 'Rubber duck',
    category: 'Decor',
    color: '#ffd04f',
    description: 'Qualified to supervise. X for its opinion.',
  },
  {
    id: 'wall',
    name: 'Wall',
    category: 'House',
    color: '#edc9a0',
    description: 'Supports everything. Except responsibility.',
  },
  {
    id: 'window',
    name: 'Window wall',
    category: 'House',
    color: '#77c7d0',
    description: 'For a clearer view of the mess.',
  },
  {
    id: 'door',
    name: 'Door',
    category: 'House',
    color: '#d78450',
    description: 'Install first. Slam later.',
  },
  {
    id: 'roof',
    name: 'Roof',
    category: 'House',
    color: '#e47851',
    description: 'Keeps the rain on the outside.',
  },
  {
    id: 'floor',
    name: 'Floor',
    category: 'House',
    color: '#d7b27d',
    description: 'Solid ground. Almost level.',
  },
  {
    id: 'sofa',
    name: 'Sofa',
    category: 'Furniture',
    color: '#e5ad3e',
    description: 'Flies well. Sits even better.',
  },
  {
    id: 'table',
    name: 'Table',
    category: 'Furniture',
    color: '#c1976b',
    description: 'Four legs. No plan.',
  },
  {
    id: 'chair',
    name: 'Chair',
    category: 'Furniture',
    color: '#71aa9a',
    description: 'For the really important breaks.',
  },
  {
    id: 'bed',
    name: 'Bed',
    category: 'Furniture',
    color: '#88b9c0',
    description: 'After a hard day, a soft landing.',
  },
  {
    id: 'plant',
    name: 'Plant',
    category: 'Decor',
    color: '#70a865',
    description: 'The only thing here with proper roots.',
  },
  {
    id: 'lamp',
    name: 'Floor lamp',
    category: 'Decor',
    color: '#f0cd79',
    description: 'Maybe it will give you a bright idea.',
  },
  {
    id: 'toilet',
    name: 'Toilet',
    category: 'Decor',
    color: '#dce8e4',
    description: 'Even a throne needs a home.',
  },
  {
    id: 'workbench',
    name: 'Workbench',
    category: 'Furniture',
    color: '#be9463',
    description: 'Heavy. But not bolted down.',
  },
  {
    id: 'barrow',
    name: 'Wheelbarrow',
    category: 'Decor',
    color: '#e8b644',
    description: 'Carrying works too. Somehow.',
  },
  {
    id: 'cone',
    name: 'Traffic cone',
    category: 'Decor',
    color: '#ee8c4d',
    description: 'Secures the site. Flies if necessary.',
  },
  {
    id: 'pallet',
    name: 'Pallet',
    category: 'House',
    color: '#c69560',
    description: 'A solid piece of delivery chaos.',
  },
  {
    id: 'bricks',
    name: 'Brick stack',
    category: 'House',
    color: '#c58460',
    description: 'Please do not sort these with your feet.',
  },
  {
    id: 'bone',
    name: 'Bone',
    category: 'Decor',
    color: '#f6ecd3',
    description: 'Who ordered the site dog?',
  },
] as const;
