import type { ItemKind } from '../types';
export type ItemDefinition = {
  kind: ItemKind;
  name: string;
  model: string;
  size: 'small' | 'large';
  essential: boolean;
  floats: boolean;
  rack?: string;
  mass: number;
};
export const ITEM_DEFINITIONS: Record<ItemKind, ItemDefinition> = {
  rope: {
    kind: 'rope',
    name: 'Rescue rope',
    model: 'rope-coil',
    size: 'large',
    essential: true,
    floats: true,
    rack: 'rescue-line',
    mass: 4,
  },
  rod: {
    kind: 'rod',
    name: 'Fishing rod',
    model: 'fishing-rod',
    size: 'large',
    essential: true,
    floats: true,
    rack: 'rod-rack',
    mass: 2,
  },
  'bait-bucket': {
    kind: 'bait-bucket',
    name: 'Bait bucket',
    model: 'bait-bucket',
    size: 'large',
    essential: true,
    floats: true,
    rack: 'bait-table',
    mass: 6,
  },
  lantern: {
    kind: 'lantern',
    name: 'Deck lantern',
    model: 'deck-lantern',
    size: 'small',
    essential: false,
    floats: true,
    mass: 2,
  },
  timber: {
    kind: 'timber',
    name: 'Repair timber',
    model: 'timber-planks',
    size: 'large',
    essential: true,
    floats: true,
    rack: 'repair-bench',
    mass: 9,
  },
  hammer: {
    kind: 'hammer',
    name: 'Repair hammer',
    model: 'claw-hammer',
    size: 'small',
    essential: true,
    floats: false,
    rack: 'repair-bench',
    mass: 2,
  },
  bailer: {
    kind: 'bailer',
    name: 'Bailer',
    model: 'wooden-bailer',
    size: 'small',
    essential: true,
    floats: true,
    rack: 'bilge-pump',
    mass: 2,
  },
  'fuel-can': {
    kind: 'fuel-can',
    name: 'Fuel can',
    model: 'fuel-can',
    size: 'large',
    essential: true,
    floats: true,
    rack: 'fuel-port',
    mass: 8,
  },
  'ice-box': {
    kind: 'ice-box',
    name: 'Ice box',
    model: 'ice-box',
    size: 'large',
    essential: true,
    floats: true,
    rack: 'ice-hold',
    mass: 12,
  },
  'landing-net': {
    kind: 'landing-net',
    name: 'Landing net',
    model: 'landing-net',
    size: 'large',
    essential: true,
    floats: true,
    rack: 'net-rack',
    mass: 3,
  },
  chart: {
    kind: 'chart',
    name: 'Sea chart',
    model: 'rolled-chart',
    size: 'small',
    essential: true,
    floats: true,
    rack: 'chart-table',
    mass: 1,
  },
  compass: {
    kind: 'compass',
    name: 'Boat compass',
    model: 'brass-compass',
    size: 'small',
    essential: true,
    floats: false,
    rack: 'chart-table',
    mass: 1,
  },
  fish: {
    kind: 'fish',
    name: 'Fresh catch',
    model: 'species-fish',
    size: 'large',
    essential: false,
    floats: true,
    rack: 'ice-hold',
    mass: 5,
  },
};
export const LOADOUT: readonly ItemKind[] = [
  'rope',
  'rod',
  'rod',
  'rod',
  'rod',
  'bait-bucket',
  'timber',
  'hammer',
  'bailer',
  'fuel-can',
  'ice-box',
  'landing-net',
  'chart',
  'compass',
  'lantern',
];
