import type { LookStyle, LookStyleId } from './types';

export const LOOK_STYLES: Record<LookStyleId, LookStyle> = {
  storybook: {
    id: 'storybook',
    key: '1',
    label: 'Handmade storybook',
    eyebrow: 'A · WARM & TACTILE',
    description: 'Sculpted clay, painted detail and soft coastal depth.',
    palette: {
      sky: '#82b9b7',
      fog: '#a9c8b9',
      sea: '#4d928d',
      seaDeep: '#245d65',
      foam: '#e9f3dc',
      sun: '#ffd594',
      beacon: '#7ef0ce',
      ink: '#173e46',
      rock: '#70827a',
      sand: '#cda86f',
      grass: '#6f956e',
      leaf: '#477765',
      wood: '#8a5b43',
      paint: '#d96f56',
      plaster: '#dbcba6',
      metal: '#596e69',
      cloth: '#f4eedb',
      rope: '#ad8250',
      glass: '#8ef4d5',
      hand: '#dc9874',
      sleeve: '#35645e',
      fish: '#79edcf',
    },
    exposure: 1.08,
    fogDensity: 0.009,
    sunIntensity: 4.2,
    hemiIntensity: 1.9,
    roughness: 0.82,
    metalness: 0,
    clearcoat: 0.08,
    waterAmplitude: 0.28,
    waterSpeed: 0.72,
    wind: 0.55,
    rain: 0,
    edgeStrength: 0,
    ambientParticles: 70,
  },
  stormlight: {
    id: 'stormlight',
    key: '2',
    label: 'Cinematic stormlight',
    eyebrow: 'B · MOODY & DRAMATIC',
    description: 'Wet surfaces, rain curtains and powerful light contrast.',
    palette: {
      sky: '#334a59',
      fog: '#425966',
      sea: '#2f6670',
      seaDeep: '#102f3b',
      foam: '#a9ced0',
      sun: '#f2b968',
      beacon: '#77f3d7',
      ink: '#102d37',
      rock: '#536364',
      sand: '#796e5a',
      grass: '#49695d',
      leaf: '#2f514a',
      wood: '#5d453a',
      paint: '#9d5548',
      plaster: '#8c8a79',
      metal: '#677778',
      cloth: '#b9b8a8',
      rope: '#786448',
      glass: '#76f3d5',
      hand: '#ba7c66',
      sleeve: '#213f42',
      fish: '#78f5d8',
    },
    exposure: 0.98,
    fogDensity: 0.02,
    sunIntensity: 3.6,
    hemiIntensity: 1.42,
    roughness: 0.62,
    metalness: 0.03,
    clearcoat: 0.42,
    waterAmplitude: 0.6,
    waterSpeed: 1.25,
    wind: 1.25,
    rain: 1,
    edgeStrength: 0,
    ambientParticles: 34,
  },
  graphic: {
    id: 'graphic',
    key: '3',
    label: 'Graphic toy adventure',
    eyebrow: 'C · BOLD & PLAYFUL',
    description: 'Clean silhouettes, illustrated edges and bright color.',
    palette: {
      sky: '#7bcace',
      fog: '#b8d9c3',
      sea: '#51aaa4',
      seaDeep: '#287a7c',
      foam: '#efffe9',
      sun: '#ffd05a',
      beacon: '#72efc9',
      ink: '#173e46',
      rock: '#66877b',
      sand: '#dfa968',
      grass: '#71a66d',
      leaf: '#3f8469',
      wood: '#9b5e43',
      paint: '#ef7657',
      plaster: '#f0dfa8',
      metal: '#4e716b',
      cloth: '#fff4d9',
      rope: '#c28a45',
      glass: '#75f1cc',
      hand: '#e99b73',
      sleeve: '#2f7169',
      fish: '#72f0cc',
    },
    exposure: 1.16,
    fogDensity: 0.006,
    sunIntensity: 4.8,
    hemiIntensity: 2.25,
    roughness: 0.94,
    metalness: 0,
    clearcoat: 0,
    waterAmplitude: 0.2,
    waterSpeed: 0.88,
    wind: 0.8,
    rain: 0,
    edgeStrength: 1,
    ambientParticles: 24,
  },
};

export const LOOK_STYLE_IDS = Object.keys(LOOK_STYLES) as LookStyleId[];

export function styleFromShortcut(code: string): LookStyleId | null {
  if (code === 'Digit1' || code === 'Numpad1') return 'storybook';
  if (code === 'Digit2' || code === 'Numpad2') return 'stormlight';
  if (code === 'Digit3' || code === 'Numpad3') return 'graphic';
  return null;
}
