import type { Cue } from '../../../shared/audio/construction/types';
import { homeUseSounds } from './home-expansion-prompts';

const clean =
  ' Close dry Foley, playful physical timing, clear short decay. No speech, music, harsh alarm or cinematic boom.';
function effect(
  id: string,
  name: string,
  group: string,
  source: string,
  trigger: string,
  duration = 1.5,
  volume = 0.8,
  loop = false,
): Cue {
  return {
    id,
    name,
    group,
    prompt: source + clean,
    trigger,
    duration,
    volume,
    loop,
    text: '',
    category: loop ? 'ambience' : 'event',
    priority: 'core',
  };
}
function line(
  id: string,
  name: string,
  text: string,
  trigger: string,
  group = 'Crew voices',
  prompt = '[playfully]',
): Cue {
  return {
    id: 'speech.' + id,
    name,
    group,
    prompt,
    text,
    trigger,
    duration: 5,
    volume: 0.85,
    loop: false,
    category: 'speech',
    priority: 'detail',
  };
}
export const INSPECTION_LINES = {
  building: ['inspection.building.missing', 'inspection.building.complete'],
  delivery: ['inspection.delivery.missing', 'inspection.delivery.complete'],
  spills: ['inspection.spills.none', 'inspection.spills.some'],
} as const;
export const AWARD_LINES: Record<string, string> = {
  'Most helpful pair': 'award.helpers',
  'Biggest spill': 'award.spill',
  'Rescue crew': 'award.rescue',
  'Air freight department': 'award.throw',
};

export function partyCatalog(): Cue[] {
  const effects = [
    effect(
      'party.ready',
      'Hard hat ready',
      'Crew lobby',
      'A worker gently taps a hard hat twice with a gloved finger, a confident little plastic tok-tok.',
      'A builder changes to Ready.',
      0.6,
      0.6,
    ),
    effect(
      'party.start',
      'Shift starts',
      'Crew lobby',
      'A small mechanical desk bell rings once, followed by a clipboard being snapped shut. Brisk and cheerful.',
      'Host starts the crew shift.',
      1.2,
    ),
    effect(
      'party.handle',
      'Take a handle',
      'Crew handling',
      'A work glove closes around a carrying handle with fabric compression, a strap tug and one small hardware clack.',
      'A builder takes a free crew role.',
      0.7,
      0.65,
    ),
    effect(
      'party.lift',
      'Lift together',
      'Crew handling',
      'Two fabric straps tighten together, the loaded frame creaks and its feet lift off with two tiny scuffs.',
      'Both roles become ready to work; also solo helper lift.',
      1.2,
    ),
    effect(
      'party.release',
      'Release a handle',
      'Crew handling',
      'A gloved hand lets a carrying strap slacken: cloth slide, a small buckle tap and the frame settling.',
      'A builder releases a crew role.',
      0.8,
      0.6,
    ),
    effect(
      'party.sofa.move',
      'Sofa · Carrying creaks',
      'Sofa shuffle',
      'Quiet rhythmic upholstered sofa frame creaks and muffled spring flex as two people carry it. Stable close texture, seamless loop, no footsteps.',
      'While the shared sofa is actually moving.',
      5,
      0.45,
      true,
    ),
    effect(
      'party.glass.move',
      'Glass · Frame under strain',
      'Handle with panic',
      'Very quiet intact glass panel vibration within rubber carrying grips, occasional faint frame ticks. Stable texture, seamless loop, no breakage.',
      'While the shared glass is moving.',
      5,
      0.4,
      true,
    ),
    effect(
      'party.crane.move',
      'Crane · Working motor',
      'Your other left',
      'A modest electric lifting winch runs steadily, low gear hum and restrained loaded cable creak. Seamless loop without start or stop.',
      'Crew crane moving; roof crane travelling or lifting.',
      6,
      0.5,
      true,
    ),
    effect(
      'party.barrow.move',
      'Barrow · Squeaky wheel',
      'Express cement',
      'A loaded wheelbarrow wheel turns with a slightly uneven rubber rumble and a quiet axle squeak on each revolution. Seamless steady loop.',
      'While the crew wheelbarrow moves.',
      5,
      0.5,
      true,
    ),
    effect(
      'party.ladder.move',
      'Ladder · Climbing rungs',
      'Hold it steady',
      'Slow work boots shifting weight up aluminium ladder rungs, hollow muted rung knocks and light rail flex. Seamless steady loop.',
      'While the climber is actively making progress.',
      4,
      0.55,
      true,
    ),
    effect(
      'party.strain',
      'Load wobble warning',
      'Crew handling',
      'A loaded carrying strap gives a tense short fabric creak, followed by two nervous little wooden frame ticks.',
      'Load crosses the wobble warning threshold; at most once per wobble.',
      1,
    ),
    effect(
      'party.sofa.spill',
      'Sofa · Unscheduled landing',
      'Sofa shuffle',
      'A sofa lands heavily on its padded side: low upholstered thump, separate wooden foot knock and one embarrassed muffled spring squeak.',
      'Shared sofa spills.',
      1.8,
    ),
    effect(
      'party.glass.crack',
      'Glass · First crack',
      'Handle with panic',
      'One short fine fracture zips through a large glass panel with a sharp restrained tick and tiny stressed pane tremble. Pane stays in frame.',
      'First damaging spill of crew glass.',
      1.2,
    ),
    effect(
      'party.glass.break',
      'Glass · Broken delivery',
      'Handle with panic',
      'A glass delivery pane breaks into small pieces: one brittle crack followed by a short falling glass tinkle. Modest volume, no explosive crash.',
      'Second damaging spill of crew glass.',
      2,
    ),
    effect(
      'party.barrow.spill',
      'Barrow · Cement everywhere',
      'Express cement',
      'A wheelbarrow tips: metal tray clonk, four paper cement bags tumble out with soft weighty thuds and powdery paper rustling.',
      'Cement bags spill from the shared barrow.',
      2.5,
    ),
    effect(
      'party.ladder.fall',
      'Ladder · Failed confidence',
      'Hold it steady',
      'An aluminium ladder wobbles with two hollow rung clacks, followed by a harmless padded workwear landing and a tiny helmet tap.',
      'Support released while the builder is climbing.',
      1.7,
    ),
    effect(
      'party.collect',
      'Pick up spilled cement bag',
      'Express cement',
      'Gloves gather a fallen paper cement bag: heavy paper crinkle, soft powder shifting and a short gritty scrape as it lifts.',
      'One spilled bag is collected.',
      1.2,
      0.7,
    ),
    effect(
      'party.recover',
      'Delivery rescued',
      'Crew handling',
      'A heavy load is levered upright: short frame creak, two solid seating taps and slack straps flicking away.',
      'A builder recovers the delivery.',
      1.4,
    ),
    effect(
      'party.delivered',
      'Delivery accepted',
      'Crew handling',
      'A wooden delivery stamp lands with one satisfying clack, followed by a small cheerful bicycle bell ping.',
      'Crew delivery completes, including the ladder sign.',
      1.5,
    ),
    effect(
      'party.card.reveal',
      'Open secret envelope',
      'Secret cards',
      'One small paper envelope is opened: crisp flap peel and a folded card sliding out with a fine paper flutter.',
      'Only this player opens their private card.',
      0.8,
      0.6,
    ),
    effect(
      'party.card.done',
      'Secret task completed',
      'Secret cards',
      'A small rubber stamp presses onto a paper card with a quiet rubber tok and a pleased little paper flick.',
      'Only the card owner hears their task completion.',
      0.7,
      0.65,
    ),
    effect(
      'timer.minute',
      'One minute · Clock warning',
      'Countdown',
      'Three evenly spaced muted wooden clock knocks, clear and mildly impatient, no harsh buzzer.',
      'Crossing 60 seconds remaining in a timed round.',
      1.3,
      0.65,
    ),
    effect(
      'timer.lastCall',
      'Thirty seconds · Last call',
      'Countdown',
      'A small wind-up alarm clock gives a brief restrained double bell rattle, then its mechanism stops. Comic urgency, never shrill.',
      'Last call begins or a timed round crosses 30 seconds.',
      1.2,
      0.7,
    ),
    effect(
      'timer.ten',
      'Ten seconds · Final stretch',
      'Countdown',
      'A clockwork ratchet winds quickly and lands on one firm wooden tick, a compact signal to hurry.',
      'Crossing 10 seconds remaining.',
      0.8,
      0.7,
    ),
    effect(
      'timer.tick',
      'Last seconds · Single tick',
      'Countdown',
      'One clearly defined mechanical clock escapement tick with a short wooden case resonance. Exactly one tick, no tock or background.',
      'Once each second from 9 to 1; no catch-up burst.',
      0.5,
      0.6,
    ),
    effect(
      'timer.end',
      'Tools down · Bell',
      'Countdown',
      'One small brass workshop bell rings twice in quick succession and decays gently. A friendly end-of-shift bell, not a fire alarm.',
      'Timed building ends, including the inspection transition.',
      2,
      0.8,
    ),
    effect(
      'inspection.arrive',
      'Inspector arrives',
      'Inspection',
      'A clipboard opens, a pen clicks and two measured work boot steps stop beside the build.',
      'Inspection begins.',
      1.5,
      0.7,
    ),
    effect(
      'inspection.stamp',
      'Verdict stamp',
      'Inspection',
      'One oversized rubber approval stamp lands on a wooden clipboard with a satisfying dry thock and a small paper shake.',
      'Inspection reveals its final verdict.',
      0.8,
      0.8,
    ),
    effect(
      'inspection.award',
      'Award reveal',
      'Inspection',
      'A little brass desk bell ping and two restrained wooden applause-like clacks. A tiny ceremony, no crowd.',
      'An award is presented after the verdict.',
      1.2,
      0.65,
    ),
    effect(
      'voice.join',
      'Voice connected',
      'Voice chat',
      'Two gentle walkie-talkie relay clicks with a tiny breath of filtered static, welcoming and brief.',
      'Local voice connection succeeds.',
      0.5,
      0.45,
    ),
    effect(
      'voice.leave',
      'Voice disconnected',
      'Voice chat',
      'One soft walkie-talkie relay release and a tiny static tail. Quiet and unambiguous.',
      'Local voice connection closes.',
      0.5,
      0.4,
    ),
    effect(
      'voice.radio',
      'Radio button down',
      'Voice chat',
      'A handheld radio push-to-talk switch clicks once with a very short low static puff. No transmitted voice.',
      'Local radio transmission starts; once per press.',
      0.5,
      0.3,
    ),
    effect(
      'capture.start',
      'Clip recording starts',
      'Clips & postcards',
      'A compact camera record switch makes two light mechanical clicks.',
      'Local clip recording starts.',
      0.5,
      0.4,
    ),
    effect(
      'capture.saved',
      'Clip ready',
      'Clips & postcards',
      'A compact camera latch snaps closed with a small satisfied click.',
      'Local clip becomes available to save.',
      0.5,
      0.45,
    ),
    effect(
      'prop.fridge.use',
      'Fridge · Anything in here?',
      'House interactions',
      'A compact fridge door opens with a rubber seal peel, a bottle rattles hopefully on the empty shelf, then the door closes with a cushioned magnetic clunk.',
      'Use a nearby fridge with X or the prop button.',
      2.4,
    ),
    effect(
      'prop.washer.use',
      'Washer · Mini spin disaster',
      'House interactions',
      'A small washing machine starts a comically uneven short spin: switch click, drum accelerates into three rubber-damped wobbly cabinet knocks, then coasts to a stop.',
      'Use a nearby washing machine; short cycle with automatic stop.',
      4.5,
      0.7,
    ),
    effect(
      'prop.clock.use',
      'Clock · Wind and chime',
      'House interactions',
      'A grandfather clock key winds with three brass ratchet clicks, a hesitant clockwork pause, then one slightly wonky warm brass chime.',
      'Use a nearby grandfather clock.',
      3,
      0.7,
    ),
    effect(
      'prop.duck.use',
      'Duck · Expert opinion',
      'House interactions',
      'A real rubber bath duck is squeezed once: short nasal air squeak with a tiny breathy tail as the rubber reinflates. Funny imperfect pitch.',
      'Use a nearby rubber duck.',
      0.9,
      0.65,
    ),
    effect(
      'prop.toilet.use',
      'Toilet · Plumbing inspection',
      'House interactions',
      'A ceramic toilet flush handle clicks, water swirls with one short hollow gulp, then a little refill trickle stops. No bodily sounds.',
      'Use a nearby toilet.',
      3.5,
      0.65,
    ),
    effect(
      'prop.lamp.use',
      'Lamp · Bright idea',
      'House interactions',
      'A floor lamp pull switch clicks twice, with a tiny shade fitting rattle between clicks. No electrical arcing.',
      'Use a nearby floor lamp.',
      0.9,
      0.65,
    ),
  ];
  const voices = [
    line(
      'crew.start',
      'Foreman · Shift starts',
      'Hard hats on. Expectations down. Let us build!',
      'New crew shift; before incidental quips.',
    ),
    line(
      'crew.lift',
      'Crew · Lift together',
      'On three! Was that three?',
      'Shared load becomes workable; rate limited.',
    ),
    line(
      'crew.spill',
      'Crew · Gravity test',
      'That was a controlled landing. Mostly.',
      'A crew load spills; suppressed during player conversation.',
    ),
    line(
      'crew.recover',
      'Crew · Recovery',
      'Same delivery. Fresh optimism.',
      'Delivery is recovered.',
    ),
    line(
      'crew.delivered',
      'Crew · Delivered',
      'Delivered! We are calling that intentional.',
      'Crew task completes.',
    ),
    line(
      'timer.minute',
      'Foreman · One minute',
      'One minute! Finish the house before the house finishes us.',
      '60-second warning.',
      'Countdown voices',
    ),
    line(
      'timer.lastCall',
      'Foreman · Last call',
      'Thirty seconds! Hide the spare screws!',
      'Last call begins.',
      'Countdown voices',
      '[excited]',
    ),
    line(
      'timer.ten',
      'Foreman · Ten seconds',
      'Ten seconds! Decorative panic only!',
      '10-second warning.',
      'Countdown voices',
      '[excited]',
    ),
    line(
      'inspection.arrive',
      'Inspector · Opening line',
      'Right. Let us see what you meant to build.',
      'Inspection opening.',
      'Inspector',
      '[curious]',
    ),
    line(
      'inspection.building.complete',
      'Inspector · All parts present',
      'All the building parts are here. An encouraging start.',
      'First inspection station: building complete.',
      'Inspector',
    ),
    line(
      'inspection.building.missing',
      'Inspector · Missing parts',
      'A few building parts appear to be on an extended lunch break.',
      'First inspection station: building incomplete.',
      'Inspector',
    ),
    line(
      'inspection.delivery.complete',
      'Inspector · Delivery arrived',
      'The special delivery arrived. Against several predictions.',
      'Second inspection station: delivery complete.',
      'Inspector',
    ),
    line(
      'inspection.delivery.missing',
      'Inspector · Delivery missing',
      'Your special delivery has not reached its final destination.',
      'Second inspection station: delivery incomplete.',
      'Inspector',
    ),
    line(
      'inspection.spills.none',
      'Inspector · Suspiciously tidy',
      'No spilled deliveries. Suspiciously professional.',
      'Third inspection station: no spills.',
      'Inspector',
    ),
    line(
      'inspection.spills.some',
      'Inspector · Gravity research',
      'The ground has been thoroughly tested. Thank you for your research.',
      'Third inspection station: at least one spill.',
      'Inspector',
    ),
    line(
      'award.helpers',
      'Award · Most helpful pair',
      'Most helpful pair! A rare case of coordinated competence.',
      'Most helpful pair award.',
      'Awards',
    ),
    line(
      'award.spill',
      'Award · Biggest spill',
      'Biggest spill! Gravity sends its congratulations.',
      'Biggest spill award.',
      'Awards',
    ),
    line(
      'award.rescue',
      'Award · Rescue crew',
      'Rescue crew! Never underestimate picking it up again.',
      'Rescue crew award.',
      'Awards',
    ),
    line(
      'award.throw',
      'Award · Air freight',
      'Air freight department! Delivery times improved. Accuracy pending.',
      'Air freight department award.',
      'Awards',
    ),
  ];
  const arrangements = [
    [
      'lobby',
      'Crew lobby',
      '96 BPM, friendly waiting-room groove, pizzicato bass, muted guitar and tiny brushed snare, space between phrases.',
      'Waiting in the crew lobby.',
      48,
    ],
    [
      'lastCall',
      'Last call · Hold my hard hat',
      '138 BPM, busy pizzicato strings, marimba and restrained woodblock percussion, playful urgency with large gaps for speech. No alarm or clock samples.',
      'Last 30 seconds of timed building.',
      32,
    ],
    [
      'inspection',
      'Inspection · Raised eyebrow',
      '82 BPM, curious bassoon, muted pizzicato strings and sparse vibraphone, comic investigative pauses, very sparse under spoken commentary.',
      'During the customer inspection.',
      40,
    ],
    [
      'results',
      'Results · The tea break',
      '94 BPM, relaxed acoustic guitar, brushed drums and warm plucked bass, affectionate exhausted celebration.',
      'After the result sting finishes.',
      48,
    ],
    [
      'build.alt1',
      'Building · Toolbox swing',
      '104 BPM, light swing on acoustic guitar, upright bass and wooden percussion, relaxed repetitive work groove.',
      'Alternate free-building arrangement.',
      60,
    ],
    [
      'build.alt2',
      'Building · Wonky workshop',
      '98 BPM, playful marimba ostinato, soft muted brass answers and brushed percussion, understated and spacious.',
      'Second alternate free-building arrangement.',
      60,
    ],
    [
      'challenge.alt1',
      'Crew job · Furniture fandango',
      '118 BPM, nimble nylon guitar, pizzicato bass, restrained shaker and woodblocks, comic teamwork momentum.',
      'Alternate timed job arrangement.',
      60,
    ],
    [
      'challenge.alt2',
      'Crew job · Measure once',
      '122 BPM, plucked strings, light clarinet answers and dry hand percussion, buoyant busy teamwork with pauses.',
      'Second alternate timed job arrangement.',
      60,
    ],
    [
      'lastCall.alt1',
      'Last call · Unscheduled efficiency',
      '140 BPM, plucked bass, nimble marimba and skittering brushes, escalating comic bustle while leaving speech frequencies clear. No alarms or ticking.',
      'Alternate final 30-second arrangement.',
      32,
    ],
    [
      'lobby.alt1',
      'Crew lobby · Waiting for Dave',
      '92 BPM, jaunty nylon guitar, lightly tapped cups and plucked bass, comfortable anticipation with a mischievous clarinet phrase.',
      'Alternate crew lobby arrangement.',
      48,
    ],
  ] as const;
  const music: Cue[] = arrangements.map(
    ([id, name, direction, trigger, duration]) => ({
      id: 'music.' + id,
      name,
      group: 'Party soundtrack',
      prompt: `Original instrumental music for a funny cooperative house-building game. ${direction} No vocals, speech or sound effects. Consistent dynamics, seamless loop-friendly start and end, no big intro or final cadence.`,
      trigger,
      category: 'music',
      text: '',
      volume: 0.8,
      loop: true,
      duration,
      priority: id.includes('.alt') ? 'variation' : 'core',
      ...(id.includes('.alt')
        ? { variantOf: 'music.' + id.split('.')[0] }
        : {}),
    }),
  );
  const homeEffects = homeUseSounds.map(([kind, name, source, duration]) =>
    effect(
      `prop.${kind}.use`,
      name,
      'House interactions',
      source,
      `Use a nearby ${kind} with X or the prop button.`,
      duration,
    ),
  );
  return [...effects, ...homeEffects, ...voices, ...music];
}

/** Existing physical cues get separately generated takes without changing saved defaults. */
export function variations(cues: Cue[]): Cue[] {
  const ids = [
    'step.concrete',
    'step.dirt',
    'event.bonk',
    'material.sofa.impact',
    'material.wood.place',
    'material.wall.place',
    'material.duck.impact',
    'prop.duck.use',
    'party.handle',
    'party.glass.crack',
    'party.barrow.spill',
  ];
  return cues
    .filter((c) => ids.includes(c.id))
    .flatMap((c) =>
      [1, 2].map((n) => ({
        ...c,
        id: `${c.id}.alt${n}`,
        name: `${c.name} · Take ${n + 1}`,
        variantOf: c.id,
        priority: 'variation' as const,
        prompt: `${c.prompt.replace(clean, '').slice(0, 315)} ${n === 1 ? 'A separate take with a slightly softer attack and lower natural resonance.' : 'A separate take with a quicker contact and slightly brighter natural resonance.'} No music or speech.`,
        trigger: `Alternates with ${c.name}; avoids repeating the same take back to back.`,
      })),
    );
}
