import type { ItemKind } from './types';

const en = {
  title: 'Sample Stampede',
  start: 'Let’s shop!',
  resume: 'Keep shopping',
  paused: 'Shopping break',
  ready: 'Your three-minute shopping dash',
  objective:
    'You drive the red cart. Your AI partner helps collect. Finish your list, then drive to the checkout marked on the radar to score. Most points wins.',
  keyboard:
    'WASD / arrows: steer, forward and reverse. Hold Shift to drift. Space / E: grab or swat.',
  touch:
    'Drag the left stick to drive and reverse. Hold Drift with your right thumb; tap Grab to collect or swat.',
  tips: 'Grab listed goods beside the shelves. Active sample stands give a speed boost. Carrying a teddy? Grab near a rival to throw it into their cart before checkout.',
  help: 'How to play',
  settings: 'Settings',
  close: 'Close',
  pause: 'Pause game',
  list: 'Shopping list',
  red: 'You · Red',
  blue: 'Blue',
  closing: 'Store closes in',
  checkout: 'Checkout',
  you: 'You',
  samples: 'Samples',
  mass: 'Cart mass',
  light: 'Light load',
  heavy: 'Heavy load',
  extreme: 'Heavy drift',
  approved: 'Approved!',
  rejected: 'Remove the teddy!',
  contraband: 'Teddy on board — swat it into a rival cart.',
  restart: 'Restart round',
  restartTitle: 'Start a new round?',
  restartText: 'Your current score and shopping list will be reset.',
  draw: 'It’s a draw!',
  error: 'The warehouse could not be displayed.',
  errorHelp:
    'Try reloading the game. Make sure hardware acceleration is enabled in your browser.',
  reload: 'Reload game',
  stand: 'Fresh samples at stand',
  returnToStore: 'Back to the yard',
  collected: 'collected',
};
const de: typeof en = {
  title: 'Sample Stampede',
  start: 'Los geht’s!',
  resume: 'Weiter einkaufen',
  paused: 'Einkaufspause',
  ready: 'Drei Minuten Einkaufsrennen',
  objective:
    'Du steuerst den roten Wagen. Dein KI-Partner hilft beim Sammeln. Erfülle deine Liste und fahre zur markierten Kasse, um zu punkten. Die meisten Punkte gewinnen.',
  keyboard:
    'WASD / Pfeiltasten: lenken, vorwärts und rückwärts. Shift halten: driften. Leertaste / E: greifen oder schlagen.',
  touch:
    'Ziehe den linken Stick zum Fahren und Rückwärtsfahren. Halte rechts Drift; tippe auf Greifen zum Sammeln oder Schlagen.',
  tips: 'Greife neben Regalen nach Waren auf deiner Liste. Aktive Probierstände geben einen Turbo. Teddy an Bord? Greife neben einem Gegner, um ihn vor der Kasse in dessen Wagen zu werfen.',
  help: 'Spielanleitung',
  settings: 'Einstellungen',
  close: 'Schließen',
  pause: 'Spiel pausieren',
  list: 'Einkaufsliste',
  red: 'Du · Rot',
  blue: 'Blau',
  closing: 'Ladenschluss in',
  checkout: 'Kasse',
  you: 'Du',
  samples: 'Kostproben',
  mass: 'Wagengewicht',
  light: 'Leichte Ladung',
  heavy: 'Schwere Ladung',
  extreme: 'Starker Drift',
  approved: 'Abgerechnet!',
  rejected: 'Teddy entfernen!',
  contraband: 'Teddy an Bord — schlage ihn in einen gegnerischen Wagen.',
  restart: 'Runde neu starten',
  restartTitle: 'Neue Runde starten?',
  restartText: 'Dein Punktestand und deine Einkaufsliste werden zurückgesetzt.',
  draw: 'Unentschieden!',
  error: 'Die Lagerhalle konnte nicht angezeigt werden.',
  errorHelp:
    'Lade das Spiel erneut. Prüfe, ob die Hardwarebeschleunigung deines Browsers aktiviert ist.',
  reload: 'Spiel neu laden',
  stand: 'Frische Kostproben an Stand',
  returnToStore: 'Zurück zum Spielehof',
  collected: 'gesammelt',
};
export const STAMPEDE_UI = { en, de };
export const ITEM_NAMES: Record<string, Record<ItemKind, string>> = {
  en: {
    paper_towels: 'Paper towels',
    kibble_50lb: 'Dog kibble',
    mega_soda: 'Mega soda',
    cereal_box: 'Sugar loops',
    giant_teddy: 'Giant teddy',
    sample_taquito: 'Taquito',
    sample_pizza_bagel: 'Pizza bagel',
    sample_churro: 'Churro',
    sample_cheese: 'Cheese',
  },
  de: {
    paper_towels: 'Küchenrollen',
    kibble_50lb: 'Hundefutter',
    mega_soda: 'Limonade',
    cereal_box: 'Frühstücksringe',
    giant_teddy: 'Riesen-Teddy',
    sample_taquito: 'Taquito',
    sample_pizza_bagel: 'Pizza-Bagel',
    sample_churro: 'Churro',
    sample_cheese: 'Käse',
  },
};
