import {
  common,
  steps,
  bed,
  effect,
  speech,
  music,
} from '../../../shared/audio/catalog-helpers';
import { salvageCues } from '../../../shared/audio/salvage-prompts';
import { stackDetailCatalog } from './detail-catalog';
const stack = [
  ...salvageCues(),
  ...steps(['sand', 'wood', 'metal', 'fabric', 'water']),
  bed(
    'site',
    'Shoreline surf',
    'Gentle seawater washing a sandy island shore, soft broad breaking foam and small pebbles retreating, open coastal air.',
    0.8,
  ),
  bed(
    'trees',
    'Coastal wind',
    'Soft steady sea breeze through sparse island foliage and grass, airy open wind with fine leaf friction. No microphone wind buffeting.',
    0.55,
  ),
  bed(
    'flood',
    'Rising flood · water movement',
    'Close water lapping around solid salvage, irregular small hollow sloshes and trickles between timber supports; mild current, no storm.',
    0.65,
  ),
  bed(
    'crane',
    'Crane motor · moving',
    'Small working yard crane winch under a moderate load, subdued steady electric motor and slow cable spool texture. No startup or stopping transient.',
    0.6,
  ),
  effect(
    'event.jump',
    'Jump',
    'Movement',
    'Boot soles push off firm ground; brief cloth movement and a small dry scuff, one restrained effort, no vocalization.',
    0.65,
    0.45,
  ),
  effect(
    'event.land',
    'Landing',
    'Movement',
    'Two boots land with bent knees; solid cushioned ground contact, a faint clothing jostle, modest body weight, no bone impact.',
    0.8,
  ),
  effect(
    'event.splash',
    'Enter water',
    'Movement',
    'An adult steps down into waist-deep seawater, one broad realistic splash, lower water displacement and a short spray of falling droplets.',
    2,
  ),
  effect(
    'event.crane-hook',
    'Attach crane hook',
    'Crane',
    'A heavy steel crane hook seats into a lifting strap; one metal clink, strap tension and a short chain rattle. No motor.',
    1.4,
  ),
  effect(
    'event.crane-release',
    'Release crane hook',
    'Crane',
    'A tensioned lifting hook unseats, small steel latch clack and slack chain settling, no falling object impact.',
    1.2,
  ),
  effect(
    'event.crane-stop',
    'Crane brake',
    'Crane',
    'A small electric winch winds down quickly and its brake gently catches, short mechanical clunk under tension.',
    1.1,
    0.5,
  ),
  effect(
    'event.flood',
    'Flood begins',
    'Round events',
    'Water rushes over a low sand lip; a contained realistic surge spreading outward followed by gentle bubbling. No siren or explosion.',
    3,
    0.8,
  ),
  effect(
    'event.rescue',
    'Help a teammate up',
    'Round events',
    'Firm gloved grip on a wet sleeve, fabric stretching and two stabilizing boot contacts as an adult is helped to stand.',
    1.5,
  ),
  speech(
    'start',
    'Round begins',
    'Sixty seconds to build. Keep a way up for everyone.',
    '[encouraging]',
  ),
  speech(
    'flood',
    'Water rising',
    'The water is rising. Head for higher ground.',
    '[urgent]',
  ),
  speech('wave', 'Call the crew', 'Over here! I can use a hand.', '[calling]'),
  speech(
    'rescue',
    'Teammate rescued',
    'Got you. Let’s get you up.',
    '[reassuring]',
  ),
  speech(
    'danger',
    'Teammate in trouble',
    'Someone needs help down there!',
    '[urgent]',
  ),
  speech('win', 'Crew safe', 'We made it. The whole crew wins!', '[excited]'),
  speech(
    'fail',
    'Try again',
    'Close one. Let’s build a better way up.',
    '[warmly]',
  ),
];
export const stackCatalog = [
  ...common,
  ...stack,
  ...music('stack-or-sink'),
  ...stackDetailCatalog,
];
