import type { Cue } from '../../../shared/audio/types';

export const driveThruCatalog: Cue[] = [
  // Event sound effects (ElevenLabs text-to-sound-effects)
  {
    id: 'event.speaker-crackle',
    name: 'Drive-thru speaker crackle',
    group: 'Intercom',
    category: 'event',
    prompt:
      'Aggressive crackling walkie-talkie speaker box squelch, radio static hiss, and distorted intercom audio buzz. Authentic fast-food drive-thru audio texture.',
    text: '',
    duration: 1.5,
    loop: false,
    volume: 0.85,
  },
  {
    id: 'event.car-horn',
    name: 'Sedan car horn',
    group: 'Car Crew',
    category: 'event',
    prompt:
      'Comedic tinny dual-tone beat-up car horn honking impatiently twice, brief echo in a concrete drive-thru lane.',
    text: '',
    duration: 1.2,
    loop: false,
    volume: 0.8,
  },
  {
    id: 'event.fan-belt',
    name: 'Screeching alternator belt',
    group: 'Car Crew',
    category: 'event',
    prompt:
      'Shrill rhythmic squeal of a loose automotive alternator fan belt slipping under acceleration, high-pitched mechanical friction squeak.',
    text: '',
    duration: 2.0,
    loop: false,
    volume: 0.75,
  },
  {
    id: 'event.toddler-toy',
    name: 'Squeaky toddler toy',
    group: 'Car Crew',
    category: 'event',
    prompt:
      'Rapid comedic rubber duck squeaking in a car backseat, frantic high-pitched plastic squawks.',
    text: '',
    duration: 1.5,
    loop: false,
    volume: 0.7,
  },
  {
    id: 'event.grill-sizzle',
    name: 'Burger patty sizzling',
    group: 'Kitchen',
    category: 'event',
    prompt:
      'Raw ground beef patty slapping onto a screaming hot commercial flat-top grill, violent grease spitting and steady crackling sizzle.',
    text: '',
    duration: 2.5,
    loop: false,
    volume: 0.8,
  },
  {
    id: 'event.patty-flip',
    name: 'Spatula burger flip',
    group: 'Kitchen',
    category: 'event',
    prompt:
      'Metal grill spatula scrapes under a burger patty, flips it with an airborne whoosh and a wet slap back down on sizzling steel.',
    text: '',
    duration: 1.2,
    loop: false,
    volume: 0.85,
  },
  {
    id: 'event.shake-vent',
    name: 'Milkshake pressure release',
    group: 'Kitchen',
    category: 'event',
    prompt:
      'Sharp pneumatic hiss and steam venting from a pressurized stainless steel soft-serve dispenser release valve.',
    text: '',
    duration: 1.4,
    loop: false,
    volume: 0.75,
  },
  {
    id: 'event.shake-explode',
    name: 'Violent milkshake blowout',
    group: 'Fail States',
    category: 'event',
    prompt:
      'Violent pressurized eruption of thick creamy strawberry milkshake bursting across the kitchen with a wet foam splat and spray.',
    text: '',
    duration: 2.2,
    loop: false,
    volume: 0.9,
  },
  {
    id: 'event.fryer-splash',
    name: 'Fryer basket immersion',
    group: 'Kitchen',
    category: 'event',
    prompt:
      'Wire basket of cut frozen potatoes dunked into boiling deep fryer oil, intense bubbly frying roar and sizzling oil eruption.',
    text: '',
    duration: 2.0,
    loop: false,
    volume: 0.8,
  },
  {
    id: 'event.pole-crash',
    name: 'Speaker pole impact',
    group: 'Fail States',
    category: 'event',
    prompt:
      'Sedan metal bumper smashes into a steel drive-thru intercom pole with a hollow denting crunch, screeching metal, and electrical short sparks.',
    text: '',
    duration: 2.2,
    loop: false,
    volume: 0.95,
  },
  {
    id: 'event.windshield-splat',
    name: 'Windshield milkshake splatter',
    group: 'Fail States',
    category: 'event',
    prompt:
      'Heavy gooey milkshake splatters across an automotive windshield with a wet gloop, followed by windshield wiper squeaks.',
    text: '',
    duration: 1.8,
    loop: false,
    volume: 0.85,
  },
  {
    id: 'event.grease-fire',
    name: 'Kitchen grease fire eruption',
    group: 'Fail States',
    category: 'event',
    prompt:
      'Deep fryer oil hits flashpoint with a deep fiery whoosh, followed by a loud fast-food kitchen fire alarm siren.',
    text: '',
    duration: 2.5,
    loop: false,
    volume: 0.9,
  },
  {
    id: 'event.curb-plop',
    name: 'Drink tray dropped down curb',
    group: 'Fail States',
    category: 'event',
    prompt:
      'Four cardboard soda cups and paper burger bag tumble off a tray and splash wetly into a concrete street gutter drain with a cartoon hollow clunk.',
    text: '',
    duration: 2.0,
    loop: false,
    volume: 0.85,
  },
  {
    id: 'event.short-stop-reach',
    name: 'Passenger window lean effort',
    group: 'Car Crew',
    category: 'event',
    prompt:
      'Fabric creaking, belt leather groaning under strain, and an adult vocal grunt straining to reach out a car window.',
    text: '',
    duration: 1.5,
    loop: false,
    volume: 0.75,
  },
  {
    id: 'event.order-served',
    name: 'Triumphant service bell',
    group: 'Round events',
    category: 'event',
    prompt:
      'Crisp double service bell ding with cheerful diner register drawer chime, celebrating successful order fulfillment.',
    text: '',
    duration: 1.8,
    loop: false,
    volume: 0.85,
  },

  // Spoken lines (ElevenLabs voice generation)
  {
    id: 'speech.welcome',
    name: 'Drive-thru greeting',
    group: 'Announcer',
    category: 'speech',
    prompt: '[upbeat, fast-food speaker, slightly crackly]',
    text: 'Welcome to Jumble Burger, home of the Quadruple Slab. Order when you are ready.',
    duration: 3.5,
    loop: false,
    volume: 0.85,
  },
  {
    id: 'speech.intercom-scramble',
    name: 'Scrambled order prompt',
    group: 'Announcer',
    category: 'speech',
    prompt: '[frustrated, shouting through static]',
    text: 'I said extra ranch on a sponge, four diet waters and no ice!',
    duration: 4.0,
    loop: false,
    volume: 0.85,
  },
  {
    id: 'speech.fire-alert',
    name: 'Grease fire warning',
    group: 'Announcer',
    category: 'speech',
    prompt: '[panicked, shouting]',
    text: 'Grease fire at the fryer! Hit the suppression button now!',
    duration: 3.2,
    loop: false,
    volume: 0.9,
  },
  {
    id: 'speech.order-ready',
    name: 'Order up announcement',
    group: 'Announcer',
    category: 'speech',
    prompt: '[cheerful, rushed]',
    text: 'Order up at the window! Watch out for the curb gap!',
    duration: 3.0,
    loop: false,
    volume: 0.85,
  },

  // Continuous beds
  {
    id: 'ambience.drive-thru-lane',
    name: 'Drive-thru lane ambience',
    group: 'Ambience',
    category: 'ambience',
    prompt:
      'Hum of idling sedan engines, distant highway traffic, neon sign transformer buzz, and muffled speaker box static in a suburban fast food parking lot.',
    text: '',
    duration: 10.0,
    loop: true,
    volume: 0.35,
  },
  {
    id: 'ambience.kitchen-chaos',
    name: 'Fast food kitchen ambience',
    group: 'Ambience',
    category: 'ambience',
    prompt:
      'Continuous sizzling grill surface, fryer oil bubbling, refrigerator compressor hum, and kitchen order ticket printer ticking.',
    text: '',
    duration: 10.0,
    loop: true,
    volume: 0.35,
  },

  // Music
  {
    id: 'music.drive-thru-rush',
    name: 'Drive-thru rush theme',
    group: 'Music',
    category: 'music',
    prompt:
      'Upbeat quirky fast-tempo comedic cartoon surf-rock with twangy guitars, bouncy slap bass, and driving percussion suitable for cooking panic.',
    text: '',
    duration: 15.0,
    loop: true,
    volume: 0.25,
  },
];
